from pathlib import Path
import json,re,collections
R=Path(__file__).resolve().parents[4]; O=Path(__file__).resolve().parent.parent; E=O/'evidence'
inv=json.loads((E/'inventory.json').read_text())
def cite(path,line=1):
 return f'[{path}:{line}](../../../{path}#L{line})'
def match(path,needle):
 lines=(R/path).read_text().splitlines()
 for i,s in enumerate(lines,1):
  if needle in s:return cite(path,i)
 raise ValueError((path,needle))
def sk(name):return next(x['path'] for x in inv if x['frontmatter']['name']==name)
def s(name,needle):return match(sk(name),needle)
def write(name,text): (O/name).write_text(text.strip()+'\n')
# Purpose; distinct-value/overlap; triggering assessment; issue/action. Static review, not behavioral scores.
data={
'contract-auditor':('Static implementation/contract mismatch audit','QE is runtime; this is static','Deliberately explicit dispatch, too restrictive for solo','Expose standalone read-only audit; keep runtime QE separate'),
'contract-author':('Versioned API/data/event/type boundaries','Plan-builder supplies intent; backend consumes','Broad contract terms fit; body rejects solo despite portable flag','Remove multi-agent-only prerequisite in solo branch; preserve contract change protocol'),
'git-commit':('Conventional commits and branch naming','git-pr owns PR creation','Commit/branch triggers distinct','Do not assume Claude trailers or invent session identity on other hosts'),
'git-post-merge-cleanup':('Classify merged branches/worktrees safely','repo-cleanup-loop schedules broader cleanup','Explicit cleanup with dry-run is appropriate','Move orphan-tag deletion after confirmation; tags do not record source-branch identity'),
'git-pr':('Create/update PR with format and checklist','git-commit handles local history','PR-specific; sensible','gh pr view --head is unsupported; use positional branch or pr list --head'),
'git-pr-feedback':('Triage review comments, implement and reply','babysit repeatedly invokes review workflow','Review feedback distinct from creation','Author reply is not resolution; inspect unresolved threads and follow-ups'),
'babysit':('Poll PR review/CI/rebase state','git-pr-feedback is one pass; controller substrate','Explicit opt-in poll appropriate','External cadence, merge permission, lock and bounded fix attempts required'),
'codebase-exploration-loop':('Iteratively map unfamiliar subsystems','repo-deep-dive produces reference series','Explicit exploration loop, not casual orientation','Run one subsystem per attended pass; novelty/provenance and bounded saturation stop'),
'contract-conformance-loop':('Generate until acceptance contract passes','contract-auditor static vs QE runtime','Mission dispatch prevents accidental expensive loop','Need independent verifier session; mutable criterion booleans alone are not proof'),
'coverage-loop':('Raise meaningful test coverage to target','QE checks behavior; coverage is supplemental','Coverage target explicit','Protect denominator/config/exclusions and existing assertions; require behavioral tests'),
'dependency-health-loop':('Recurring audit/update/test dependency health','dependency-coordinator aligns packages before build','Explicit recurring health scope','Pin lock state; distinguish outage from vulnerability; approval before major updates/publishing'),
'fix-until-green':('Fix one root cause until full gates pass','diagnose-loop discovers cause; this converges gates','Dispatch-only contradicts user trigger promises on generic hosts','Immutable verifier commands, external caps, full final proof; no skipped-gate green'),
'loop-controller':('Select loop substrate and required safety contract','Foundation, not merge with concrete loops','Explicit harness design appropriate','Host adapter, real externally enforced budgets and separate evaluator required'),
'migration-loop':('Enumerated transforms with expand-contract staging','db-migration-agent handles database safety','Wide refactor mission triggers appropriate','Handle grep rc 0/1/2; freeze patterns/scope; source/error cannot count as zero'),
'nightly-docs-and-changelog':('Scheduled docs/changelog maintenance','docs-agent writes once; living-plan tracks work','Nightly opt-in, not every docs ask','One-shot doc pass without scheduler; freshness evidence and bounded diff/PR review'),
'orchestrator-task-loop':('Drain task DAG with per-task proof','orchestrator coordinates; fix-until-green inner loop','Explicit Agent Teams queue scope appropriate','File-backed queue/dependency locks; native event templates are not installed enforcement'),
'perf-loop':('Profile and optimize against repeatable budget','performance-agent measures one pass','Explicit performance target','Freeze dataset/workload/hardware/config; compare distributions plus functional regression'),
'repo-cleanup-loop':('Periodic hygiene with classified safe deletion','git-post-merge-cleanup handles git/worktrees','Recurring cleanup separate from one-shot','Preview and approve deletes; do not infer ignored credentials are disposable'),
'self-healing-loop':('Observe health and attempt bounded recovery','No incident-response coordination skill','Watch/heal explicit, operationally sensitive','Read-only monitoring until scoped approved action; refuse autonomous prod changes'),
'madness':('Intent front-door router with cost consent','skill-explorer recommends rather than launches','One unresolved decision and no-skill option good','Fallback note exists but frontend/review/plan routes still target gated or solo-rejecting skills'),
'model-adaptation':('Model prompting, effort, refusal and handoff doctrine','use-freellmapi wires endpoint; caveman trims output','Model-change/optimization terms fit','Add GPT/Gemini/unknown references; probe provider instead of silent Anthropic default'),
'skill-catalog':('Disk-derived catalog/count reconciliation','sync-skills changes global delivery','Catalog drift intent precise','Shell-only catalog overgated; installed skill lacks root catalog tooling'),
'skill-explorer':('Recommend skill by unresolved decision','madness invokes; this helps discovery','Browse vs execute distinction good','Filter recommendations by available capability/adapter rather than tool-name assumption'),
'skill-review':('Audit skill quality, references and triggering','skill-creator measures; skill-update edits','Review intent precise','Do not call static descriptions proven triggerable; reuse eval coverage and root health tooling'),
'skill-update':('Human-approved precise skill revisions','skill-writer drafts; review diagnoses','Edit/review distinction sensible','Portable skill suggests unavailable subagents; standalone edits safe; root resources need resolver'),
'skill-writer':('Draft PSFS skills with positive justified rules','skill-creator adds measured iteration','Create overlaps creator; route simple vs empirical','Clarify writer vs creator route; reconcile words vs tokens and export resource conventions'),
'orchestrator':('Contract-first ownership/implementation/QA coordination','Plan-builder creates plan; controller loops','Explicit expensive build opt-in good','Split execution adapters, specify sequential state transitions and independent QA; shrink always-loaded body'),
'backend-agent':('API/business/data implementation','contract-author defines boundaries','Orchestrator-only blocks standalone API work','Opening says produces API contract while inputs require authored contract; add solo mode'),
'code-review-agent':('Independent Standards and Spec review lanes','security static security, QE runtime','Already explicit standalone, not build default','Remove host gate; sequential lanes exist but same-context isolation is degraded'),
'db-migration-agent':('Database schema/migration/seed safety','migration-loop is wide code transform','Orchestrator-only unnecessary for solo migration','Portable migration checklist; no unattended data-loss/production changes'),
'docs-agent':('Run/setup/API docs and changelog','interactive-doc adds HTML; nightly-docs recurring','Orchestrator-only too restrictive','Portable docs pass; preserve agents/ADR carve-outs and verify instructions'),
'frontend-agent':('Contract-bound mobile-first UI implementation','ui-brief specifies; guards lint; render-sanity observes','disable + orchestrator-only traps portable doctrine','Standalone first-class mode, scoped CSS/DRY guard bootstrap before page multiplication'),
'infrastructure-agent':('Containers/CI/service wiring','deployment-checklist validates rather than writes','Orchestrator-only prevents solo infra','Portable infra pass; deployment/observability score claims do not exist in QE schema'),
'observability-agent':('Structured logging/health/metrics/alerts','infra wires transport; backend business behavior','Orchestrator-only unnecessary','Portable instrumentation pass; advisory score statement already correct, do not reopen FA8'),
'performance-agent':('Reproducible load/profile report','perf-loop optimizes iteratively','Orchestrator-only prevents budget diagnosis','Portable measurement mode; advisory QE dimension wording already correct'),
'qe-agent':('Runtime conformance/integration/adversarial QA','contract-auditor is static, not duplicate','Dispatch-only blocks standalone real verification','Prototype skip/lower-threshold advice conflicts with hard canonical gate; independent solo reviewer'),
'security-agent':('Read-only static security/dependency audit','QE confirms runtime exploitability','Dispatch-only prevents standalone audit','Portable security review with report-only privileges; root scanner not bundled'),
'architecture-rescue':('Deletion-test architectural simplification review','zoom-out orientation, yagni prevention','Overbuild rescue triggers focused','Keep small read-only analysis; proposed deletion is not authorization'),
'artifact-publish':('Publish self-contained hosted artifact','interactive-doc creates paired content','Share-link intent belongs here','Keep Claude native Artifact adapter; portable local HTML or approved hosting not equivalent privacy'),
'caveman':('Persistent terse communication mode','yagni minimizes build, not wording','Explicit terse/off phrases good','Keep, per existing ADR; persist mode across handoff, do not omit evidence for brevity'),
'class-extraction-guard':('Detect repeated utility-class runs','design guard values; duplicate declarations separate','Organization triggers accurate for utilities','Unique classes defeat intended DRY; extend CSS declarations; warning baseline/config need protected policy'),
'claude-design-brief':('Canvas-oriented hi-fi/A-B-C design prompt','ui-brief production spec','Claude Design canvas scope explicit','Keep vendor-specific destination; do not silently redirect requested canvas to plain UI brief'),
'context-manager':('Compaction and disk-backed role handoffs','maintain-context glossary; wiki durable knowledge','Context/handoff intent focused','Portable handoff schema and AGENTS paths; gate currently hides host-neutral protocol'),
'dependency-coordinator':('Cross-package dependency version contract','dependency-health monitors later','Parallel monorepo trigger appropriate','Shell/files only: portable pre-build pass usable solo; profile path adapter'),
'deployment-checklist':('Evidence-based READY/NOT READY preflight','railway deploy acts; this validates','Deploy readiness trigger good','Portable read-only release check; missing QA must be blocked, not fabricated'),
'design-token-guard':('Source styling/token policy audit/scaffold','class-extraction structural organization','Styling trigger focused; compatibility mislabels CC','HTML dimension miss/default WARN, staged-error allow, CSS opt-in; strict configured policy catches inline'),
'diagnose-loop':('Deterministic reproduction plus falsifiable hypotheses','fix-until-green convergence; systematic-debugging broader','Bug/repro scope distinctive','Visible browser capability fallback; recipe says disable tests, must mean filter execution not weaken suite'),
'find-unknowns':('Blindspot research and post-change comprehension quiz','grill-me resolves known opinions; zoom-out maps','Before/after routing explicit, keep distinct','Quiz requires human answer; web/browser unavailable means disclose skipped evidence'),
'grill-me':('Depth-first one-question decision interview','find-unknowns discovers questions first','Non-trivial-change wording broad; specific phrases help','Keep human response gate; no self-answering; no code edits'),
'interactive-doc':('Canonical Markdown plus faithful interactive HTML','artifact-publish sharing; mermaid diagrams','Explainer/wiki-page overlaps llm-wiki, use output intent','Conditional CDN imports contradict offline/self-contained claim; diagram parity check'),
'living-plan':('Front-door/roadmap/ledger/archive/intake setup','plan-builder creation; intake approved findings','Existing file access explicitly not setup, good','Root template not bundled on install; preserve current-project boundary and approval before intake'),
'llm-wiki':('Setup/ingest/query/lint persistent knowledge base','wiki-research reads; deep-dive analyzes source','Wiki knowledge intent clear','CLAUDE.md-only detection/schema invisible on other hosts; add AGENTS route plus source freshness'),
'maintain-context':('Term glossary and gated ADR maintenance','context-manager sessions; not same memory','Three-condition ADR rule filters overtrigger','Missing setup policy contradicts fail-loud setup requirement; explicit user override needed'),
'mermaid-charts':('Question-driven technical diagrams','interactive-doc rendering','Broad visualize trigger overlaps doc, one-output route','Checklist has render proof but no allowed shell/browser tool; add renderer capability or user evidence'),
'nano-banana':('Gemini image generation with bundled API helper','frontend uses output; not general text generation','Image intent clear','Script lookup hardcodes ~/.claude; installed copies lose root env discovery; dated model/cost/Imagen claim unverified'),
'payload-cms':('Version-pinned Payload website build/clone/debug routing','official payload generic; this websites/pitfalls','Headless CMS without Payload broad false-positive risk','Keep dense versioned refs and observed proof; select Payload first, not every CMS mention'),
'plan-builder':('Synthesize research/goals into architectural build plan','writing-plans external solo TDD; living-plan maintenance','Make a plan broad but body multi-agent only','Portable flag/body solo rejection and external solo handoff need honest plan-only path'),
'plan-intake':('Dedup/actionable approval before ledger edits','living-plan convention; brief expands approved item','Explicit intake phrases good','Keep fail-closed approver-readable filter; do not auto-intake this audit'),
'playwright':('Visible-browser E2E/screenshots and structured proof','render-sanity semantic health; not same output','E2E/screenshot trigger appropriate','Honor existing manager; npm init/install example unsafe bootstrap; browser alternative capability needed'),
'project-profiler':('Verified project run/profile context','repo-deep-dive long reference; setup config','Onboard overlap setup; two complementary outputs','Host-neutral file/shell work gated; canonical AGENTS profile projection'),
'prose-slop-guard':('Lexical prose checks plus independent voice review','docs-agent writes, reviewer grades','Humanize broad but outward prose scoped','Markup exemptions can game lexical score; require provenance/reviewer; assets delivery missing'),
'railway-deploy':('Railway container/config/CLI/API deployment','deployment-checklist preflight','Platform-specific, distinct','Require approval before installs/deploy; current-project root env differs from library credential convention'),
'render-sanity':('Observe broken text/links/auth states in real UI','UX subjective polish; QE broad runtime','Semantic smoke intent clear','Portable browser adapter; first-item sample does not prove every link; absent sign-in method is BLOCKED when outside scope'),
'repo-deep-dive':('Source-backed technical reference series','zoom-out small map, wiki retrieval','Deep-dive phrase too broad if output only orientation','Portable sequential subsystem passes; bounded vault read permission; no automatic ledger writes'),
'settings-consolidator':('Claude permission consolidation/autonomy bootstrap','not capability-detect; permissions are authority','Stop prompting me too consequential to auto-authorize','Keep CC-specific; approval before broad global allowlist/home scan; deny list is not portable sandbox'),
'setup-project-skills':('Persist domain/contract/tracker choices','project-profiler detects facts; setup asks choices','Explicit invocation correct','Unify missing-config policy with consumers; preserve idempotent no-overwrite behavior'),
'skill-creator':('Draft/eval/optimize empirical skills','writer quick drafting; review static','Broad overlaps writer/update; benchmark scope distinctive','Hermes-only runner despite portable flag; description candidate unused; forced load/text heuristic and holdout selection invalidate trigger scores'),
'sync-skills':('Link/copy raw repo skills to global homes','converter transforms; catalog reconciles source','Sync intent good; CC flag hides Cursor operation','Only CC/Cursor here; flattened link ignores subset, collisions rm-rf, cleanup unowned broken links'),
'ui-brief':('Opinionated UI spec with moat/real-path DoD','claude-design-brief canvas; implementation frontend','Written brief intent explicit','Portable output but Claude production language/routes; preserve positive shared primitives and real-path DoD'),
'use-freellmapi':('Reversibly wire model proxy and prove real call','model-adaptation decides policy; pxpipe lossy compression','App OR harness supported, contrary sibling prose','Live catalog avoids roster guesses; remote pipe-to-shell requires opt-in; free quota/privacy not zero risk'),
'use-pxpipe':('Opt-in lossy context proxy with cache verification','freellmapi endpoint routing, not compression','Claude session cost scope explicit','Legit CC-only adapter; preserve fail-closed glyph allowlist, fix sibling app-only misdescription'),
'website-walkthrough-video':('Capture/pan route-complete website videos','Playwright verifies UI behavior; tour is presentation','Video output scope clear','Only Node/ffmpeg/Playwright: overgated; full-page memory bounds contradict sibling capture discipline'),
'wiki-research':('Targeted wiki-first just-in-time context','llm-wiki maintains, repo-deep-dive fills gaps','Broad review/build context by design','Wiki sufficiency cannot prove current code; revision/freshness check before safety/correctness use'),
'work-item-brief':('Durable behavioral task brief with AFK/HITL','plan-intake creates ledger items','Dispatch-ready brief scope focused','Absolute path ban useful for stale tickets but immutable evidence/safety scope should survive by artifact refs'),
'yagni-gate':('Persistent minimal-build ladder without losing safety','caveman speech, rescue post-hoc architecture','Explicit minimal mode, negative examples good','Read-only allowed-tools cannot execute required runnable check; declare advisory composition or shell gate'),
'zoom-out':('Read-only higher-level module connections','architecture-rescue recommends change','Explicit-only no auto-fire, good','Keep tiny; existing ADR keeps despite upstream deletion; no forced 50-word padding'),
}
assert len(data)==76, len(data)
keep={'architecture-rescue','caveman','claude-design-brief','find-unknowns','grill-me','plan-intake','zoom-out','work-item-brief','yagni-gate','payload-cms'}
# Exact extra citations where one line explains the defect; all rows also cite full body and metadata.
extra={
'frontend-agent':s('frontend-agent','requires_claude_code'), 'qe-agent':s('qe-agent','skip the QA gate'),
'backend-agent':s('backend-agent','You produce the API contract'), 'infrastructure-agent':s('infrastructure-agent','deployment/observability'),
'git-pr':s('git-pr','gh pr view --head'), 'git-pr-feedback':s('git-pr-feedback','Already-replied comments'),
'git-post-merge-cleanup':s('git-post-merge-cleanup','git tag -d'), 'orchestrator':s('orchestrator','**Sequential mode**'),
'skill-creator':match('skills/workflows/skill-creator/scripts/run_eval.py','description: str'),
'design-token-guard':match('skills/workflows/design-token-guard/scripts/check_design_tokens.py','DIM_RE ='),
'class-extraction-guard':s('class-extraction-guard','minUtilities'), 'plan-builder':s('plan-builder','For single-agent'),
'contract-author':s('contract-author','For single-agent'), 'madness':s('madness','else `frontend-agent`'),
'nano-banana':s('nano-banana','find -L ~/.claude'), 'website-walkthrough-video':s('website-walkthrough-video','full-page'),
'llm-wiki':s('llm-wiki','No `CLAUDE.md`'), 'setup-project-skills':s('setup-project-skills','Do not silently'),
'maintain-context':s('maintain-context','default to single-context'), 'wiki-research':s('wiki-research','Wiki covers it'),
'use-pxpipe':s('use-pxpipe','The **app'), 'interactive-doc':s('interactive-doc','CDN imports'),
}
head='''# Skill-by-skill matrix — W1

Baseline: 76 active skills, at HEAD `51106e1`; six archives excluded. Every active body was inspected. See [inventory](evidence/inventory.json), [numbered complete bodies](evidence/all-active-skills-numbered.txt), and [supporting excerpts](evidence/supporting-source-numbered.txt).

**Verification limits:** “keep” means the purpose and static procedure are sound, not a measured model efficacy claim. Live triggering/efficacy for every row is **UNVERIFIED**. No paid model tasks were launched. Script/resource existence and selected adversarial paths were checked; every supporting reference's substantive correctness was not exhaustively runtime-tested. “Fix” preserves the useful skill, not archive-by-default. No skill merits archiving on present evidence; merges/splits below concern doctrine/adapter placement, not deletion of specializations.

Capabilities: R=read/search, W=write/edit, S=shell, F=web fetch/search, A=subagent, P=parallel/fresh-context reviewer, T=shared tasks/messages, C=completion gate, Q=human clarification, M=disk memory, B=visible browser, U=artifact publish, L=lifecycle hooks, N=scheduler. Body requirements may exceed allowed-tools; this is itself a portability issue. CC=Claude Code; Other=non-Claude converter path. CC “designed” is not a live host smoke. Other “blocked” means excluded from conversion, not that the host lacks equivalent capabilities. Other “degraded” includes resource/route limitations, even for portable flags.

Size column is **body words / full file lines / reference-file count**; words are NOT tokens. All active files have fewer than 500 physical lines; orchestrator is 5,463 body words. Agent Skills recommends fewer than 5,000 **tokens**, so several bodies warrant token measurement. Trigger column is static collision analysis, not precision/recall.

| Skill / category | Purpose and distinct value (overlap) | Verdict / issue | Capability dependencies | Delivery status | Trigger assessment | Size W/L/refs | Evidence / severity |
|---|---|---|---|---|---|---|---|
'''
rows=[]
for x in inv:
 n=x['frontmatter']['name']; p=x['path']; purpose,overlap,trigger,issue=data[n]; cat=p.split('/')[1]; tools=x['frontmatter'].get('allowed-tools',[]); caps=['R']
 if any(t in tools for t in ['Write','Edit']): caps+=['W']
 if 'Bash' in tools:caps+=['S']
 if any(t in tools for t in ['WebFetch','WebSearch']):caps+=['F']
 if 'Agent' in tools or cat in ['loops','orchestrator']:caps+=['A','P']
 if cat in ['loops','orchestrator']:caps+=['C','M','Q']
 if n in ['babysit','dependency-health-loop','nightly-docs-and-changelog','repo-cleanup-loop','self-healing-loop']:caps+=['N']
 if n in ['orchestrator-task-loop','orchestrator']:caps+=['T','L']
 if n in ['playwright','render-sanity','frontend-agent','qe-agent','ui-brief','website-walkthrough-video','diagnose-loop','payload-cms']:caps+=['B']
 if n in ['grill-me','find-unknowns','plan-intake','setup-project-skills','settings-consolidator']:caps+=['Q']
 if n=='artifact-publish':caps+=['U']
 if n in ['llm-wiki','wiki-research','context-manager','maintain-context','living-plan']:caps+=['M']
 if n in ['class-extraction-guard','design-token-guard','prose-slop-guard','deployment-checklist']:caps+=['C']
 gated=x['frontmatter'].get('requires_claude_code',False); status='CC designed; Other blocked' if gated else 'CC/Other portable doctrine; delivery degraded'
 verdict='keep' if n in keep else 'fix'
 if n=='orchestrator':verdict='split doctrine/adapters'
 sev='P1' if gated and n not in ['settings-consolidator','use-pxpipe','artifact-publish'] else 'P2'
 if n in keep:sev='P3' if n not in ['payload-cms','yagni-gate'] else 'P2'
 ev=extra.get(n,cite(p,1)); rows.append(f'| [{n}](../../../{p}) / {cat} | {purpose}. {overlap}. | **{verdict}**: {issue}. | {", ".join(dict.fromkeys(caps))} | {status} | {trigger}. | {x["body_words"]}/{x["lines"]}/{len(x["references"])} | {ev}; full body {cite(p,20)} / **{sev}** |')
write('01-skill-matrix.md',head+'\n'.join(rows)+'''

## Resource and cross-reference resolution

[Literal resource misses](evidence/literal-resource-misses.json) are candidates, **not** 57 broken links: sibling loop references are qualified by `loop-controller`, cross-skill files by their owning skill, and root scripts explicitly by the repository. Manual refutation prevents treating those as missing resources. Actual distribution gaps remain: root catalog/health/scanner/template helpers are not bundled; flat layouts do not preserve relative resource paths; all assets and skill-creator's `agents/` / `eval-viewer/` are omitted by directory-copy conversion. See [toolchain](07-toolchain.md).

Dependency graph: contract-author → implementation roles → contract-auditor static → QE runtime → deployment-checklist. Find-unknowns before/after is not grill-me; class-extraction utility runs are not token policy; code-review Standards/Spec lanes are not security-only audit. Keep these distinctions. Prefer widening their execution modes rather than replacing them with generic “universal-agent” copies.
''')
# Every actionable item, with observable-change approval column and dedup disposition.
findings=[
('UA-01','P1','M','Portable role doctrine is blocked by host and orchestrator-only gates','Add standalone/solo branches for all ten roles and contract-auditor, retaining CC dispatch, ownership and QE order','Solo builds can use the same frontend, security and verification discipline as orchestrated builds.',s('frontend-agent','requires_claude_code')+'; '+s('code-review-agent','standalone'), 'SR1 extension; PF5 clarified runtime-standalone, not user-standalone'),
('UA-02','P1','L','Binary host/plan flags discard capability-rich non-Claude runtimes','Version PSFS capability/mode schema plus one resolver used by convert/install/sync; preserve legacy CC fields during migration','Skills choose a safe execution mode based on tools actually available.',match('scripts/convert.sh','if [[ "$requires_cc"') if 'if [[ "$requires_cc"' in (R/'scripts/convert.sh').read_text() else cite('scripts/convert.sh',711),'F1/WC3 overlap: approve narrow resolver now; defer broad generator framework'),
('UA-03','P1','L','Sequential core is a paragraph contradicting no-implementation/mandatory spawn rules','Specify state graph, role packets, dependency queue, reset boundaries and independent verifier; refuse unbounded unattended fallback','Single-agent hosts can finish a bounded build without pretending the builder is an independent reviewer.',s('orchestrator','**Sequential mode**')+'; '+s('orchestrator','Never implement code yourself'),'Not new sequential-orchestrator skill; F15/F16 shared substrate overlap'),
('UA-04','P1','M','Frontend gates are available but no host-neutral build bootstrap ensures invocation','Add consented project bootstrap of strict layout/organization policy, precommit and CI; integrate solo entry and router','Styling violations are caught even when the orchestrator is not used.',s('design-token-guard','Step 3')+'; '+s('class-extraction-guard','warning severity'),'Extend existing guards; F7 hook-forge overlap, not a new hook framework'),
('UA-05','P2','M','Default design guard misses HTML dimensions and passes inline-layout warnings','Parse HTML attribute CSS and JSX separately; add layout-only ERROR profile, dynamic CSS-var exemption, honest scanned count','An inline grid or fixed-width wrapper cannot pass the frontend policy unnoticed.',match('skills/workflows/design-token-guard/scripts/check_design_tokens.py','DIM_RE =')+'; [default/strict repro](evidence/refutation-checks.txt)','New defect, no blanket ban on safe dynamic properties'),
('UA-06','P2','M','Unique class names hide duplicate CSS declaration blocks','Extend class-extraction guard with normalized declaration equivalence scoped by media/layer/specificity and approved exceptions','Copy-pasted CSS is detected even after every rule is renamed.',match('skills/workflows/class-extraction-guard/scripts/check_class_extraction.py','minUtilities')+'; [hash fixture](evidence/adversarial-results.txt)','Extend existing organization guard; no new skill required'),
('UA-07','P2','M','No generic shared-layout markup gate catches copied chrome','Add shared-layout guard over source templates, not generated HTML; require one owning partial/component/include','Changing one header or footer updates every page instead of leaving copies behind.', '[four-page reproduced escape](evidence/adversarial-results.txt); '+s('payload-cms','header, footer'),'New generic gap; Payload globals/reusable content already help in that stack'),
('UA-08','P0','S','Parallel installer worker resets dry-run and can write during a requested preview','Parse worker arguments or preserve exported flags; fake-HOME regression proving zero writes','A dry-run remains read-only in parallel mode.',match('scripts/install.sh','DRY_RUN=false')+'; [worker wrote despite dry-run](evidence/refutation-checks.txt)','New safety defect; no actual user HOME changed'),
('UA-09','P2','M','Parallel converter loses --out, totals and Gemini manifest; macOS command too long','Propagate immutable worker context after parsing, collect status/counts, emit manifest once, avoid xargs inline path expansion','Parallel generation produces the same files and failures as sequential generation.',cite('scripts/convert.sh',790)+'; [worker fixture](evidence/adversarial-results.txt); [parallel run](evidence/convert-parallel.txt)','New worker defect; not stale integrations claim'),
('UA-10','P1','M','Conversion omits assets, creator helper dirs and nested inline resources','Ship resource manifest for assets/agents/eval-viewer/templates; preserve skill-root paths or rewrite every literal reference','Installed guards and skill evaluation retain their templates and helper programs.',cite('scripts/convert.sh',109)+'; [resource summary](evidence/resource-delivery-summary.json)','PF1 shipped scripts; this is uncovered resource classes, not reopening absent script-copy fix'),
('UA-11','P1','M','Installer paths drop converted scripts/references and Gemini metadata','Make classic and plan installers consume the same resource manifest; preserve Gemini skills/ and extension manifest and hooks','A generated skill remains runnable after installation, not only in the staging folder.',cite('scripts/install.sh',540)+'; '+cite('scripts/install-plan.sh',228)+'; [741-operation plan](evidence/fresh-install-plan.json)','PF1 integration-level regression evidence: generated scripts exist but installation drops them'),
('UA-12','P0','M','Strict QA hook allows missing/crashed validator and accepts unbound stale reports','Fail closed on validator failure in enforcement mode; bind report to run/revision/contract and bounded stop reentry','A broken checker or old QA report cannot falsely certify a new build.',cite('hooks/scripts/qa-gate.sh',85)+'; [strict missing-validator repro](evidence/adversarial-results.txt)','DV1 stdin hang remains fixed; do not reopen it'),
('UA-13','P1','M','Loop hard-budget claims are prompt instructions rather than enforced ceilings on all paths','Require wrapper max calls/tokens/time/cost, locks/cancellation and proof artifacts before unattended mode','An overnight loop stops at its approved budget even when the model ignores a prompt.',s('loop-controller','watch `/cost`')+'; '+cite('skills/loops/loop-controller/references/primitives.md',143),'F9/F15/F16 overlap; implement shared enforcement, not another prose budget skill'),
('UA-14','P2','M','Gate criteria/config/baselines can be weakened by the worker','Freeze verifier/config/datasets/test assertions; reviewer authorizes changes; handle grep errors separately','A green result must reflect a real improvement rather than a narrower test or metric.',cite('skills/loops/migration-loop/references/migration-checklist.md',95)+'; '+cite('skills/loops/loop-controller/references/safety.md',97),'Existing anti-cheat doctrine is good; mechanical enforcement extension'),
('UA-15','P1','M','Model doctrine lacks GPT/Gemini/unknown and defaults silently to Anthropic','Adopt audited draft references and explicit observed provider/endpoint/effort capability policy','Changing model no longer injects nonexistent Claude settings into the run.',cite('skills/meta/model-adaptation/references/model-effort-tiering.md',83)+'; [drafts](04-model-adaptation-drafts/unknown-model-adaptation.md)','MT1/MA2 preserved; these are missing instantiations'),
('UA-16','P2','M','Cost policy forbids approved cross-vendor cheap-worker/independent-reviewer runs outside proxy','Add explicit allowed-provider/privacy/budget opt-in with model catalog and accepted-result cost measurement','The owner can approve a cheap builder plus a stronger independent reviewer without bypassing policy.',cite('skills/meta/model-adaptation/references/model-effort-tiering.md',96)+'; [ladder](04-model-adaptation-drafts/cross-vendor-tiering.md)','Policy change, not claim MT1 absent; single-provider remains default'),
('UA-17','P1','M','Skill-creator evaluates old description, forced skill loading and stdout mentions; errors look like negatives','Apply candidate in isolated snapshot; observe actual retrieval/invocation trace; model pin per worker; tri-state run outcomes and isolated HOME','Trigger scores measure whether the candidate was chosen, not whether its name appeared in an answer.',cite('skills/workflows/skill-creator/scripts/run_eval.py',75)+'; '+cite('skills/workflows/skill-creator/scripts/run_eval.py',125)+'; [mocked boundary check](evidence/refutation-checks.txt)','New installed Hermes-oriented eval runner defect; no paid model execution'),
('UA-18','P2','S','Creator selects best by repeated held-out-test scores','Use train/dev for tuning and selection; final touch-once held-out set per split-hygiene standard','A reported test improvement survives an honest unseen final check.',cite('skills/workflows/skill-creator/scripts/run_loop.py',207)+'; '+cite('docs/standards/eval-split-hygiene.md',1),'SO4 standard closed; consumer violates it, demonstrated regression'),
('UA-19','P2','L','Universality and trigger claims have no cross-host load/efficacy test','Extend F3/F5 into tiny low-cost host/model matrix with frozen baseline, held-out outcomes and budget limits','Universal support is backed by measured task results and resource-load checks.',cite('.github/workflows/lint-skills.yml',117)+'; '+cite('docs/FUTURE.md',15),'Existing F3/F5, not newly invented cross-model-eval scope'),
('UA-20','P1','M','Raw sync differs from conversion and ignores flat-link subset; collisions delete copies','Use same capability projection; ownership manifest, backup/confirm collisions and subset tests; clean only owned links','Sync only changes requested owned skills and never destroys an unrelated local copy.',cite('skills/workflows/sync-skills/scripts/sync-skills.sh',393)+'; '+cite('skills/workflows/sync-skills/scripts/sync-skills.sh',412),'Baseline CC/Cursor only, do not assert newer multihost sync'),
('UA-21','P2','M','Serializable apply trusts stale source hash, loses mode and allows destination escape','Validate plan schema/source digest/destination containment and symlink parents; preserve modes, merge state, atomic apply','A reviewed installation applies those exact bytes only within its approved destination.',cite('scripts/install-apply.sh',92)+'; [stale-hash/mode/root fixture](evidence/adversarial-results.txt)','Outside-declared-root fixture stayed inside audit directory'),
('UA-22','P2','S','PR creation uses unsupported --head flag and feedback treats replies as resolution','Use supported gh branch argument and unresolved-thread state rather than author-reply existence','PR workflows find the right PR and do not silently skip still-open feedback.',s('git-pr','gh pr view --head')+'; '+s('git-pr-feedback','Already-replied comments')+'; [gh help](evidence/adversarial-results.txt)','Read-only CLI help verified, no GitHub mutation'),
('UA-23','P2','S','Tag cleanup deletion appears before required approval and infers branch history from names','Make scan nonmutating, classify tag target reachability/retention and approve before tag deletion','Cleanup previews include tags and no remote deletion happens before consent.',s('git-post-merge-cleanup','git tag -d')+'; '+s('git-post-merge-cleanup','wait for the user'),'Ambiguous sequence, not observed unauthorized deletion'),
('UA-24','P2','S','QE prototype advice and role pipeline blurbs contradict canonical gate/schema','Remove skip/lower-threshold default; make explicit prototype acceptance policy; repair frontend UX and infra nonexistent scores/backend contract authorship','Agents agree on who authors contracts and what actually blocks completion.',s('qe-agent','skip the QA gate')+'; '+s('infrastructure-agent','deployment/observability')+'; '+s('frontend-agent','UX/contract_conformance'),'FA8 advisory closure remains correct elsewhere; residual regression lines specifically cited'),
('UA-25','P2','M','PSFS open-parser requirement and closed schema disagree with current Agent Skills types','Separate tolerant loader from strict author lint; serialize allowed-tools string and metadata string-map for standard export; tighten names','Portable exports match the live open standard without breaking native CC frontmatter.',cite('spec/PSFS.md',70)+'; '+cite('spec/frontmatter.schema.json',113)+'; [live standard](https://agentskills.io/specification)','Backward-compatible exports; do not blindly rewrite canonical arrays'),
('UA-26','P2','M','Scripts and portable bodies resolve resources through Claude home or repo root','Define SKILL_ROOT/runtime profile/secret-loader contract; bundle root helpers or declare checkout requirement; explicit env injection','Copied skills find their scripts and approved credentials without depending on ~/.claude.',s('nano-banana','find -L ~/.claude')+'; '+s('living-plan','cp template/')+'; '+s('skill-catalog','scripts/catalog.sh --sync'),'Never distribute root .env or private values'),
('UA-27','P2','S','Missing project config can mean fail-loud or silently default depending on skill','Specify one explicit-consent fallback contract for setup and consumers','Every host gets the same understandable setup requirement and override choice.',s('setup-project-skills','Do not silently')+'; '+s('maintain-context','default to single-context'),'Human-approved orchestrator default already exists, retain it'),
('UA-28','P2','S','Wiki knowledge can be treated as current-code proof without freshness check','Carry source revision/date and verify touched boundaries in current code before safety/correctness decisions','A stale wiki can guide discovery but cannot certify today’s implementation.',s('wiki-research','Wiki covers it')+'; '+s('llm-wiki','Note contradictions explicitly'),'Extend retrieval protocol, not a new knowledge system'),
('UA-29','P2','S','Walkthrough capture uses unbounded full-page images despite shared memory warning','Share screenshot height/route/bytes budget with Playwright, tile/cap or refuse oversized captures','Long websites produce bounded videos without exhausting workstation memory.',s('website-walkthrough-video','full-page')+'; '+s('playwright','8,000px'),'Not a claim that capture failed live; static missing bound'),
('UA-30','P2','S','Body word guidance and unsupported host claims outrun existing lint checks','Measure approximate tokens, validate resource closure, report physical/nonblank lines distinctly, repair scoped stale assertions','Quality claims say what was actually checked, and oversized prompts are visible before use.',cite('CLAUDE.md',60)+'; '+cite('README.md',366)+'; '+cite('START-HERE.md',8),'RV16 minimized body already; further split justified by current5463words; historic counts not drift'),
('UA-31','P2','S','Guard staged enumeration errors can return clean success','Return configuration/execution-error status when git/read fails and report true scanned file count','A checker that cannot inspect the source reports blocked, never clean.',cite('skills/workflows/design-token-guard/scripts/check_design_tokens.py',295)+'; [mock git failure](evidence/refutation-checks.txt)','Canonical failure handler warns but still returns empty list'),
('UA-32','P2','S','Portable prose contains consequential install/global-permission/deploy defaults','Require scoped approval before global bootstrap, pipe-to-shell, production requests and privacy-changing publication','Routine skills cannot expand authority or spend money just because a trigger matched.',s('settings-consolidator','Load the baseline')+'; '+s('use-freellmapi','curl -fsSL')+'; '+s('railway-deploy','npm i -g'),'F9 overlaps; explicit host adapter authority, no new autonomy skill'),
]
assert len({x[0] for x in findings})==len(findings)
ledger='''# Universal audit — candidate ledger intake

**Status: proposed only. No ledger writes, implementation, commit, or PR authorized.** Source: [executive summary](00-executive-summary.md) and linked evidence. Baseline `51106e1`, 2026-10-02. IDs UA-01–UA-32 are reserved proposals, not already accepted work.

Read the target ledger's current rules again at intake time. This report follows plan-intake's two-summary approval table: an observable plain-language change plus a concise problem/fix. Priority follows owner's rubric; size S/M/L is estimated implementation scope, not calendar time. Wave `—`, Status `proposed`, Owner `—`. Flagged parked overlaps need an explicit unpark/extension decision rather than duplicate rows. The owner must approve before any updates to REMAINING-WORK, COMPLETED-WORK or PLAN.

## Candidate approval table

| Proposed ID | Priority | Wave | Area | What it does / what you'd notice | One-line problem | Proposed fix | Evidence / source | Size | Dedup / status |
|---|---|---|---|---|---|---|---|---|---|
'''
for ID,pri,size,problem,fix,notice,evidence,dedup in findings:
 area='toolchain' if ID in ['UA-08','UA-09','UA-10','UA-11','UA-20','UA-21','UA-25','UA-26','UA-30'] else 'model/eval' if ID in ['UA-15','UA-16','UA-17','UA-18','UA-19'] else 'skills/gates'
 ledger+=f'| {ID} | {pri} | — | {area} | {notice} | {problem}. | {fix}. | {evidence} | {size} | {dedup}; proposed / — |\n'
write('09-ledger-intake.md',ledger+'''

## Intake exclusions and dependencies

Do not intake “Windsurf missing,” stale 37-skill integrations, 77-vs-79 count mismatch, missing script-copy in convert, absent MT1 tiering, absent MA2 optimizer split, missing full recursive tests, broken stdin guard, or macOS README gate overstatement as blanket defects: refuted here or already closed. START-HERE's separate blanket matrix assertion and residual schema blurbs are narrower evidence-backed issues.

Order: UA-08/12 safety first; UA-09/10/11/21 delivery correctness; UA-01/04/05/06/07 frontend outcome; UA-02/03/13/14 native-preserving execution; UA-15/16 cost/model policy; UA-17/18 before trusting UA-19 cross-model measurement. UA-19 is **F3/F5 extension**, not a second eval system. Generic model-router, sequential-orchestrator and session-handoff remain existing-doctrine/adapter extensions; no new duplicate skill tickets.
''')
(E/'finding-index.json').write_text(json.dumps([{'id':x[0],'priority':x[1],'size':x[2],'problem':x[3],'fix':x[4],'notice':x[5],'evidence':x[6],'dedup':x[7]} for x in findings],indent=2)+'\n')
print('Wrote matrix',len(rows),'and ledger',len(findings))
