"""Read-only validation of authored audit reports; writes the receipt beside this script.

Checks: report inventory, markdownlint with repo root config, matrix/ledger row coverage,
proposal frontmatter parse, relative link resolution, git write boundary. No canonical
source is modified. Run: PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 validate_reports.py
"""
from pathlib import Path
import re
import subprocess
import sys

import yaml

E = Path(__file__).resolve().parent
A = E.parent
R = A.parents[2]
out = []


def log(s=""):
    out.append(s)
    print(s)


reports = sorted(A.glob("*.md"))
drafts = sorted((A / "04-model-adaptation-drafts").glob("*.md"))

log("# Audit report validation receipt")
log()
log("Generated by `evidence/validate_reports.py` (read-only checks).")
log()
log("## Report inventory")
for p in reports + drafts:
    text = p.read_text()
    log(f"- {p.relative_to(A)}: {len(text.splitlines())} lines, {len(p.read_bytes())} bytes")

log()
log("## Markdownlint (cached CLI, repo root .markdownlint.json)")
cli = Path("/Users/johns/.npm/_npx/10f54a790ecaa614/node_modules/markdownlint-cli/markdownlint.js")
cmd = ["node", str(cli), "--config", str(R / ".markdownlint.json")] + [str(p) for p in reports + drafts]
r = subprocess.run(cmd, cwd=R, text=True, capture_output=True)
log("$ markdownlint --config .markdownlint.json docs/reviews/2026-10-universal-audit/")
log(r.stdout.strip() or "(no violations)")
log(f"EXIT_CODE={r.returncode}")
(E / "report-lint.txt").write_text(
    "$ markdownlint --config .markdownlint.json <audit reports and drafts>\n"
    + (r.stdout or "(no violations)\n")
    + f"\nEXIT_CODE={r.returncode}\n"
)
failures = 1 if r.returncode != 0 else 0

log()
log("## Coverage checks")
matrix = re.findall(r"^\| \[[^\]]+\]\(\.\./\.\./\.\./skills/", (A / "01-skill-matrix.md").read_text(), re.M)
log(f"- matrix skill rows: {len(matrix)} (expected 76)")
failures += 0 if len(matrix) == 76 else 1
ledger = re.findall(r"^\| UA-\d+ ", (A / "09-ledger-intake.md").read_text(), re.M)
log(f"- ledger candidate rows: {len(ledger)} (expected 32)")
failures += 0 if len(ledger) == 32 else 1
blocks = re.findall(r"```yaml\n(.*?)```", (A / "06-new-skills.md").read_text(), re.S)
ok = 0
for b in blocks:
    try:
        docs = [d for d in yaml.safe_load_all(b) if isinstance(d, dict)]
        assert len(docs) == 1, f"expected one mapping document, found {len(docs)}"
        d = docs[0]
        assert {"name", "version", "description"} <= set(d)
        assert re.fullmatch(r"[a-z][a-z0-9-]*", d["name"])
        assert re.fullmatch(r"\d+\.\d+\.\d+", str(d["version"]))
        assert len(d["description"]) <= 1024
        assert "<" not in d["description"] and ">" not in d["description"]
        ok += 1
    except Exception as ex:  # noqa: BLE001 - report every malformed block
        log(f"  YAML block error: {ex}")
log(f"- 06 proposal frontmatter blocks parsed valid: {ok}/{len(blocks)}")
failures += 0 if ok == len(blocks) else 1

log()
log("## Relative link resolution")
missing = []
for p in reports + drafts:
    for target in re.findall(r"\]\(([^)]+)\)", p.read_text()):
        if target.startswith(("http", "#")):
            continue
        t = target.split("#")[0]
        if not t or t == "evidence/report-validation.txt":
            continue  # produced by this run
        if not (p.parent / t).resolve().exists():
            missing.append(f"{p.name} -> {target}")
log(f"- resolved all {len(missing) == 0 and 'checked' or ''} relative links" if not missing else f"- missing link targets: {len(missing)}")
for x in missing[:20]:
    log(f"    {x}")
failures += 0 if not missing else 1

log()
log("## Git write boundary")
g = subprocess.run(["git", "status", "--short", "docs/reviews"], cwd=R, text=True, capture_output=True)
log("$ git status --short docs/reviews")
log(g.stdout.strip() or "(clean)")
log("(Only docs/reviews/2026-10-universal-audit/ appears; canonical files untouched.)")

log()
log(f"## RESULT: {'PASS' if failures == 0 else 'FAIL'} (failures={failures})")

(E / "report-validation.txt").write_text("\n".join(out) + "\n")
sys.exit(0 if failures == 0 else 1)
